# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_application.proto.example1.example1_pb2 as example1__pb2


class Example1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateData1 = channel.unary_unary(
                '/example1.Example1/CreateData1',
                request_serializer=example1__pb2.CreateData1Request.SerializeToString,
                response_deserializer=example1__pb2.CreateData1Response.FromString,
                )
        self.ReadData1 = channel.unary_unary(
                '/example1.Example1/ReadData1',
                request_serializer=example1__pb2.ReadData1Request.SerializeToString,
                response_deserializer=example1__pb2.ReadData1Response.FromString,
                )


class Example1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateData1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Example1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateData1': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateData1,
                    request_deserializer=example1__pb2.CreateData1Request.FromString,
                    response_serializer=example1__pb2.CreateData1Response.SerializeToString,
            ),
            'ReadData1': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData1,
                    request_deserializer=example1__pb2.ReadData1Request.FromString,
                    response_serializer=example1__pb2.ReadData1Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example1.Example1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Example1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateData1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example1.Example1/CreateData1',
            example1__pb2.CreateData1Request.SerializeToString,
            example1__pb2.CreateData1Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadData1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example1.Example1/ReadData1',
            example1__pb2.ReadData1Request.SerializeToString,
            example1__pb2.ReadData1Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
