# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example1.proto',
  package='example1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65xample1.proto\x12\x08\x65xample1\"2\n\x12\x43reateData1Request\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"4\n\x13\x43reateData1Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x1e\n\x10ReadData1Request\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x11ReadData1Response\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x32\xa0\x01\n\x08\x45xample1\x12L\n\x0b\x43reateData1\x12\x1c.example1.CreateData1Request\x1a\x1d.example1.CreateData1Response\"\x00\x12\x46\n\tReadData1\x12\x1a.example1.ReadData1Request\x1a\x1b.example1.ReadData1Response\"\x00\x62\x06proto3'
)




_CREATEDATA1REQUEST = _descriptor.Descriptor(
  name='CreateData1Request',
  full_name='example1.CreateData1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example1.CreateData1Request.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='example1.CreateData1Request.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=78,
)


_CREATEDATA1RESPONSE = _descriptor.Descriptor(
  name='CreateData1Response',
  full_name='example1.CreateData1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example1.CreateData1Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='example1.CreateData1Response.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=132,
)


_READDATA1REQUEST = _descriptor.Descriptor(
  name='ReadData1Request',
  full_name='example1.ReadData1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example1.ReadData1Request.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=164,
)


_READDATA1RESPONSE = _descriptor.Descriptor(
  name='ReadData1Response',
  full_name='example1.ReadData1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example1.ReadData1Response.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='example1.ReadData1Response.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='example1.ReadData1Response.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='example1.ReadData1Response.code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['CreateData1Request'] = _CREATEDATA1REQUEST
DESCRIPTOR.message_types_by_name['CreateData1Response'] = _CREATEDATA1RESPONSE
DESCRIPTOR.message_types_by_name['ReadData1Request'] = _READDATA1REQUEST
DESCRIPTOR.message_types_by_name['ReadData1Response'] = _READDATA1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateData1Request = _reflection.GeneratedProtocolMessageType('CreateData1Request', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATA1REQUEST,
  '__module__' : 'example1_pb2'
  # @@protoc_insertion_point(class_scope:example1.CreateData1Request)
  })
_sym_db.RegisterMessage(CreateData1Request)

CreateData1Response = _reflection.GeneratedProtocolMessageType('CreateData1Response', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATA1RESPONSE,
  '__module__' : 'example1_pb2'
  # @@protoc_insertion_point(class_scope:example1.CreateData1Response)
  })
_sym_db.RegisterMessage(CreateData1Response)

ReadData1Request = _reflection.GeneratedProtocolMessageType('ReadData1Request', (_message.Message,), {
  'DESCRIPTOR' : _READDATA1REQUEST,
  '__module__' : 'example1_pb2'
  # @@protoc_insertion_point(class_scope:example1.ReadData1Request)
  })
_sym_db.RegisterMessage(ReadData1Request)

ReadData1Response = _reflection.GeneratedProtocolMessageType('ReadData1Response', (_message.Message,), {
  'DESCRIPTOR' : _READDATA1RESPONSE,
  '__module__' : 'example1_pb2'
  # @@protoc_insertion_point(class_scope:example1.ReadData1Response)
  })
_sym_db.RegisterMessage(ReadData1Response)



_EXAMPLE1 = _descriptor.ServiceDescriptor(
  name='Example1',
  full_name='example1.Example1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=249,
  serialized_end=409,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateData1',
    full_name='example1.Example1.CreateData1',
    index=0,
    containing_service=None,
    input_type=_CREATEDATA1REQUEST,
    output_type=_CREATEDATA1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadData1',
    full_name='example1.Example1.ReadData1',
    index=1,
    containing_service=None,
    input_type=_READDATA1REQUEST,
    output_type=_READDATA1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE1)

DESCRIPTOR.services_by_name['Example1'] = _EXAMPLE1

# @@protoc_insertion_point(module_scope)
