# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example2.proto',
  package='example2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65xample2.proto\x12\x08\x65xample2\"2\n\x12\x43reateData2Request\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"4\n\x13\x43reateData2Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\x1e\n\x10ReadData2Request\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x11ReadData2Response\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t2\xa0\x01\n\x08\x45xample2\x12L\n\x0b\x43reateData2\x12\x1c.example2.CreateData2Request\x1a\x1d.example2.CreateData2Response\"\x00\x12\x46\n\tReadData2\x12\x1a.example2.ReadData2Request\x1a\x1b.example2.ReadData2Response\"\x00\x62\x06proto3'
)




_CREATEDATA2REQUEST = _descriptor.Descriptor(
  name='CreateData2Request',
  full_name='example2.CreateData2Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example2.CreateData2Request.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='example2.CreateData2Request.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=78,
)


_CREATEDATA2RESPONSE = _descriptor.Descriptor(
  name='CreateData2Response',
  full_name='example2.CreateData2Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example2.CreateData2Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='example2.CreateData2Response.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=132,
)


_READDATA2REQUEST = _descriptor.Descriptor(
  name='ReadData2Request',
  full_name='example2.ReadData2Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example2.ReadData2Request.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=164,
)


_READDATA2RESPONSE = _descriptor.Descriptor(
  name='ReadData2Response',
  full_name='example2.ReadData2Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example2.ReadData2Response.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='example2.ReadData2Response.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='example2.ReadData2Response.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='example2.ReadData2Response.code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['CreateData2Request'] = _CREATEDATA2REQUEST
DESCRIPTOR.message_types_by_name['CreateData2Response'] = _CREATEDATA2RESPONSE
DESCRIPTOR.message_types_by_name['ReadData2Request'] = _READDATA2REQUEST
DESCRIPTOR.message_types_by_name['ReadData2Response'] = _READDATA2RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateData2Request = _reflection.GeneratedProtocolMessageType('CreateData2Request', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATA2REQUEST,
  '__module__' : 'example2_pb2'
  # @@protoc_insertion_point(class_scope:example2.CreateData2Request)
  })
_sym_db.RegisterMessage(CreateData2Request)

CreateData2Response = _reflection.GeneratedProtocolMessageType('CreateData2Response', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATA2RESPONSE,
  '__module__' : 'example2_pb2'
  # @@protoc_insertion_point(class_scope:example2.CreateData2Response)
  })
_sym_db.RegisterMessage(CreateData2Response)

ReadData2Request = _reflection.GeneratedProtocolMessageType('ReadData2Request', (_message.Message,), {
  'DESCRIPTOR' : _READDATA2REQUEST,
  '__module__' : 'example2_pb2'
  # @@protoc_insertion_point(class_scope:example2.ReadData2Request)
  })
_sym_db.RegisterMessage(ReadData2Request)

ReadData2Response = _reflection.GeneratedProtocolMessageType('ReadData2Response', (_message.Message,), {
  'DESCRIPTOR' : _READDATA2RESPONSE,
  '__module__' : 'example2_pb2'
  # @@protoc_insertion_point(class_scope:example2.ReadData2Response)
  })
_sym_db.RegisterMessage(ReadData2Response)



_EXAMPLE2 = _descriptor.ServiceDescriptor(
  name='Example2',
  full_name='example2.Example2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=249,
  serialized_end=409,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateData2',
    full_name='example2.Example2.CreateData2',
    index=0,
    containing_service=None,
    input_type=_CREATEDATA2REQUEST,
    output_type=_CREATEDATA2RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadData2',
    full_name='example2.Example2.ReadData2',
    index=1,
    containing_service=None,
    input_type=_READDATA2REQUEST,
    output_type=_READDATA2RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE2)

DESCRIPTOR.services_by_name['Example2'] = _EXAMPLE2

# @@protoc_insertion_point(module_scope)
