# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.example2.example2_pb2 as example2__pb2


class Example2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateData2 = channel.unary_unary(
                '/example2.Example2/CreateData2',
                request_serializer=example2__pb2.CreateData2Request.SerializeToString,
                response_deserializer=example2__pb2.CreateData2Response.FromString,
                )
        self.ReadData2 = channel.unary_unary(
                '/example2.Example2/ReadData2',
                request_serializer=example2__pb2.ReadData2Request.SerializeToString,
                response_deserializer=example2__pb2.ReadData2Response.FromString,
                )


class Example2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateData2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Example2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateData2': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateData2,
                    request_deserializer=example2__pb2.CreateData2Request.FromString,
                    response_serializer=example2__pb2.CreateData2Response.SerializeToString,
            ),
            'ReadData2': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData2,
                    request_deserializer=example2__pb2.ReadData2Request.FromString,
                    response_serializer=example2__pb2.ReadData2Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example2.Example2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Example2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateData2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example2.Example2/CreateData2',
            example2__pb2.CreateData2Request.SerializeToString,
            example2__pb2.CreateData2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadData2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example2.Example2/ReadData2',
            example2__pb2.ReadData2Request.SerializeToString,
            example2__pb2.ReadData2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
